# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/article/', max_length=100, verbose_name='\u56fe\u7247')),
                ('alt', models.CharField(blank=True, default='\u8fd9\u662f\u4e00\u5f20\u95ee\u6587\u7ae0\u63d2\u56fe', max_length=100, verbose_name='\u63cf\u53d9')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('tag_state', models.CharField(default='text', max_length=50, verbose_name='\u6807\u8bb0')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('intro', models.CharField(blank=True, max_length=100, verbose_name='\u6982\u8981')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('commenta', models.CharField(blank=True, max_length=20, verbose_name='\u8bc4\u8bba\u6587\u7ae0')),
                ('commentn', models.CharField(blank=True, max_length=20, verbose_name='\u8bc4\u8bba\u65b0\u95fb')),
                ('commentm', models.CharField(blank=True, max_length=20, verbose_name='\u8bc4\u8bba\u97f3\u4e50')),
                ('commentv', models.CharField(blank=True, max_length=20, verbose_name='\u8bc4\u8bba\u7535\u5f71')),
                ('commentg', models.CharField(blank=True, max_length=20, verbose_name='\u8bc4\u8bba\u6e38\u620f')),
                ('commento', models.CharField(blank=True, max_length=20, verbose_name='\u8bc4\u8bba\u5176\u5b83')),
                ('mailto', models.CharField(blank=True, max_length=20, verbose_name='\u56de\u590d')),
                ('href', models.CharField(blank=True, max_length=20, verbose_name='\u5f15\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='G_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/game/', max_length=100, verbose_name='\u56fe\u7247')),
                ('alt', models.CharField(blank=True, default='\u8fd9\u662f\u4e00\u5f20\u6e38\u620f\u63d2\u56fe', max_length=100, verbose_name='\u63cf\u53d9')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('tag_state', models.CharField(default='text', max_length=50, verbose_name='\u6807\u8bb0')),
                ('content', models.TextField(blank=True, verbose_name='\u5185\u5bb9')),
                ('intro', models.CharField(blank=True, max_length=100, verbose_name='\u6982\u8981')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/img/', max_length=100, verbose_name='\u7528\u6237\u56fe\u6807')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('href', models.CharField(max_length=50, verbose_name='\u94fe\u63a5\u5230')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='\u5217\u8868')),
                ('tag_index', models.CharField(default='', max_length=20, verbose_name='\u6807\u8bb0')),
            ],
        ),
        migrations.CreateModel(
            name='M_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/music/', max_length=100, verbose_name='\u56fe\u7247')),
                ('alt', models.CharField(blank=True, default='\u8fd9\u662f\u4e00\u5f20\u97f3\u4e50\u63d2\u56fe', max_length=100, verbose_name='\u63cf\u53d9')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6b4c\u66f2\u540d')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u6b4c\u624b')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u6b4c\u8bcd')),
                ('tag_state', models.CharField(default='music', max_length=50, verbose_name='\u6807\u8bb0')),
                ('link', models.CharField(default='/static/music/', max_length=50, verbose_name='\u94fe\u63a5')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.List', verbose_name='\u680f\u76ee')),
            ],
        ),
        migrations.CreateModel(
            name='N_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/new/', max_length=100, verbose_name='\u56fe\u7247')),
                ('alt', models.CharField(blank=True, default='\u8fd9\u662f\u4e00\u5f20\u95ee\u65b0\u95fb\u63d2\u56fe', max_length=100, verbose_name='\u63cf\u53d9')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('tag_state', models.CharField(default='text', max_length=50, verbose_name='\u6807\u8bb0')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('intro', models.CharField(blank=True, max_length=100, verbose_name='\u6982\u8981')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.List', verbose_name='\u680f\u76ee')),
            ],
        ),
        migrations.CreateModel(
            name='O_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/other/', max_length=100, verbose_name='\u56fe\u7247')),
                ('alt', models.CharField(blank=True, default='\u8fd9\u662f\u4e00\u5f20\u56fe\u7247', max_length=100, verbose_name='\u63cf\u53d9')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('tag_state', models.CharField(default='text', max_length=50, verbose_name='\u6807\u8bb0')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('intro', models.CharField(blank=True, max_length=100, verbose_name='\u6982\u8981')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.List', verbose_name='\u680f\u76ee')),
            ],
        ),
        migrations.CreateModel(
            name='Ouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=40, verbose_name='\u5bc6\u7801')),
                ('nickname', models.CharField(max_length=20, verbose_name='\u6635\u79f0')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('ip_addr', models.CharField(default='', max_length=30, verbose_name='IP')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Img', verbose_name='\u56fe\u6807')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='\u6807\u7b7e')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u680f\u76ee')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('tag_index', models.CharField(default='', max_length=20, verbose_name='\u6807\u8bb0')),
            ],
        ),
        migrations.CreateModel(
            name='V_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/static/img/video/', max_length=100, verbose_name='\u56fe\u7247')),
                ('alt', models.CharField(blank=True, default='\u8fd9\u662f\u4e00\u5f20\u56fe\u7247', max_length=100, verbose_name='\u63cf\u53d9')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u540d')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u6f14\u5458')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u6587\u7ae0')),
                ('tag_state', models.CharField(default='video', max_length=50, verbose_name='\u6807\u8bb0')),
                ('link', models.CharField(default='/static/video/', max_length=50, verbose_name='\u94fe\u63a5')),
                ('pub_date', models.DateTimeField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.List', verbose_name='\u680f\u76ee')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', verbose_name='\u72b6\u6001')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e')),
            ],
        ),
        migrations.AddField(
            model_name='v_img',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Video', verbose_name='\u7535\u5f71\u56fe\u7247'),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='other',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='other',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='o_img',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Other', verbose_name='\u5176\u4ed6\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='new',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='n_img',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.New', verbose_name='\u65b0\u95fb\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='music',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='music',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='m_img',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Music', verbose_name='\u97f3\u4e50\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='list',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Title', verbose_name='\u4e0a\u7ea7\u680f\u76ee'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('name', 'href')]),
        ),
        migrations.AlterUniqueTogether(
            name='img',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='game',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.List', verbose_name='\u680f\u76ee'),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='g_img',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Game', verbose_name='\u6e38\u620f\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Ouser', verbose_name='\u8bc4\u8bba\u4eba'),
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.List', verbose_name='\u680f\u76ee'),
        ),
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='a_img',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='\u6587\u7ae0\u56fe\u7247'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='v_img',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='ouser',
            unique_together=set([('username', 'nickname')]),
        ),
        migrations.AlterUniqueTogether(
            name='other',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='o_img',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='new',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='n_img',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='music',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='m_img',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='g_img',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title',)]),
        ),
        migrations.AlterUniqueTogether(
            name='a_img',
            unique_together=set([('name',)]),
        ),
    ]
